package br.com.datadev.jaspertojrxml.gui;

import br.com.datadev.jaspertojrxml.util.Janela;
import br.com.datadev.jaspertojrxml.util.ModeloLista;
import br.com.datadev.jaspertojrxml.util.Relatorio;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Fabrício
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelOrigem = new javax.swing.JPanel();
        scrollOrigem = new javax.swing.JScrollPane();
        listOrigem = new javax.swing.JList();
        progressoProcessamento = new javax.swing.JProgressBar();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnProcessar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JasperToJrxml");
        setResizable(false);

        painelOrigem.setBorder(javax.swing.BorderFactory.createTitledBorder("Origem:"));

        listOrigem.setModel(new ModeloLista());
        listOrigem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollOrigem.setViewportView(listOrigem);

        javax.swing.GroupLayout painelOrigemLayout = new javax.swing.GroupLayout(painelOrigem);
        painelOrigem.setLayout(painelOrigemLayout);
        painelOrigemLayout.setHorizontalGroup(
            painelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOrigemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelOrigemLayout.setVerticalGroup(
            painelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOrigemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAdicionar.setMnemonic('a');
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setMnemonic('r');
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnProcessar.setMnemonic('p');
        btnProcessar.setText("Processar");
        btnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProcessar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressoProcessamento, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcessar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressoProcessamento, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(632, 391));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        JFileChooser buscaArquivo = new JFileChooser();
        buscaArquivo.setDialogTitle("Selecionar arquivo .jasper");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos .jasper", "jasper");
        buscaArquivo.addChoosableFileFilter(filter);
        buscaArquivo.setAcceptAllFileFilterUsed(false);
        buscaArquivo.setMultiSelectionEnabled(true);
        int resultado = buscaArquivo.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            List<Object> arquivos = new ArrayList<>(Arrays.asList(buscaArquivo.getSelectedFiles()));
            ((ModeloLista) listOrigem.getModel()).addElements(arquivos);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (listOrigem.getSelectedValue() != null) {
            ((ModeloLista) listOrigem.getModel()).removeElement(listOrigem.getSelectedIndex());
        } else {
            Janela.msgAviso("Selecione um item", "Atenção");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed
        if (listOrigem.getModel().getSize() > 0) {
            String destino = System.getProperty("user.dir");
            Relatorio relatorio;
            for (Object item : ((ModeloLista) listOrigem.getModel()).getAll()) {
                File origem = (File) item;
                try {
                    relatorio = new Relatorio(origem, destino + File.separator + origem.getName().replaceAll(".jasper", ".jrxml"));
                    relatorio.getJrxml();
                } catch (JRException ex) {
                    ex.printStackTrace();
                }
            }
            
            Janela.msgAviso("Arquivos disponíveis em:\n" + destino, "Aviso");
        }

    }//GEN-LAST:event_btnProcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnProcessar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JList listOrigem;
    private javax.swing.JPanel painelOrigem;
    private javax.swing.JProgressBar progressoProcessamento;
    private javax.swing.JScrollPane scrollOrigem;
    // End of variables declaration//GEN-END:variables
}
